theme: jekyll-theme-minimal
#github: [metadata] 
repository: warrensbox/bulk-emailerer
logo: /assets/img/logo.png
title: bulk-emailer

show_downloads: true

exclude: [vendor]

google_analytics: true

#github: [metadata] 
