theme: jekyll-theme-minimal
#github: [metadata] 
repository: warrensbox/aws-finder
logo: /assets/img/logo.png
title: aws-find

show_downloads: true

exclude: [vendor]

google_analytics: true

#github: [metadata] 
